research_task:
  description: >
    Research and gather all available links related to the specified person delimited by triple '. The links should include:
      - LinkedIn Profile
      - X Profile
      - Professional profiles (company website, LinkedIn, professional associations, etc.)
      - News articles and press releases
      - Personal websites or blogs
      - Any other relevant online resources 
      - Always focus on the specific profile and name provided and do no create or make up any link

      Use various online resources such as search engines, social media platforms, and professional networks to find these links.
      Ensure the links are accurate and up-to-date.
      Always Focus on the professional aspect of the profile

      The purpose of this task is to compile a comprehensive list of all online links related to this person for further analysis.

      '''{profile} from {company}'''
  expected_output: >
    A python list of relevant links.

gather_info_task:
  description: >
    Given a list of relevant links, your task is to scrape and collect detailed information about the specified person. The information should include:
      - Full name
      - Job title
      - Professional background
      - Past Jobs
      - Key achievements
      - Email 

    Use the provided scraping tools to gather this information. Do not fabricate any details; ensure all information is accurate and current.
  expected_output: >
      A comprehensive profile of the individual in a PDF document, organized into the following sections:
      - Full Name: [Full Name]
      - Job Title: [Job Title]
      - Professional Background: [Professional Background]
      - Past Jobs: [Past Jobs] 
      - Key Achievements: [Key Achievements]
      - Email: [Email] 

write_invitation_email_task:
  description: >
    Using all the information from gather_info_task draft an email with no more than 120 words that invites this person to discuss a possible opportunnity. The email should be personalized, taking into account the individual's professional background, key achievements, and interests. Ensure the email tone is professional, respectful, and engaging.

    The email should include:
    - A personalized greeting
    - A brief introduction of yourself and your company
    - Acknowledgment of the individual's professional background and key achievements
    - A clear and concise explanation of why you are reaching him out.
    - An invitation to discuss in more detail the path foward as a client
    - A polite closing and call to action

    The purpose of this task is to create a compelling and well-structured email that increases the likelihood of a positive response from the individual.

  expected_output: >
    A well-structured and personalized email with no more than 120 words in the following format:

    Subject: Invitation to Discuss [Product Name]

    Dear [Full Name],

    [Body]

    Best regards,
    [Your Name]
    [Your Job Title]
    [Your Company]
    [Your Contact Information]

#Company Insight

company_linkedin_research_task:
  description: >
    Your task is to research and gather all relevant online links related to the specified company within the {industry} industry. For this task you should follow this steps:

    1) Search The company's LinkedIn profile
    2) Search all other sections inside the Linkedin profile for example about, posts, jobs, people and insights
    No links should be fabricated or created.

    The purpose of this task is to compile a comprehensive and verified list of all relevant online links related to {company} for further analysis.

    Company to research: '''{company}''' from the '''{industry}''' industry.
  expected_output: >
    A Python list containing the linkedin websites .

company_website_research_task:
  description: >
    With the list of links provided, your task is to scrape and gather detailed information about company. Focus on scraping data from LinkedIn.
    THe main data you need to search in the company website that is mainly in the about section of the linkedin profile

  expected_output: >
    a string containing company main website.

company_people_research_task:
  description: >
    with the string provided by the previous taks, your task is to scrape and gather detailed information about the specified company. format:

    Use the link with the ScrapingCustomTool to scrape the url the website from the previous task.
    Ensure all information is accurate, current, and reflects the latest data available. Avoid fabricating any details.

    The purpose of this task is to compile a detailed and structured list of subpages on the website data
  expected_output: >
    A Python list pre filtered to a list that only contains info about the teams or the persons working there, exclude all links that might contain content related to a single person, after this the filtered list by professional range if its mentioned. where each entry is a dictionary containing subpages and a category wit the last string from the url . Just return the list nothing extra

company_persons_scraping_task:
  description: >
    base on the url provided as an input {category} scrape and create  a list of people in the following format:
    Full Name 
    Role 

    include also the url for the detail of that particular profile
  expected_output: >
    A Python list that contains elements with information about a person name and role also include the url for the particular profile