###
# This workflow is currently disabled
# name: Deploy to DigitalOcean

# on:
#   push:
#     branches: [ main ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       # Add your deployment steps here
###

# Placeholder to ensure file is valid YAML
name: disabled-workflow
on: workflow_dispatch
jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is currently disabled"