[server]
port = 8080
baseUrlPath = "/"
enableXsrfProtection = true
enableCORS = false

[browser]
serverAddress = "https://insight-tracker.com/"  # Replace with your domain
serverPort = 443  # Use 443 for HTTPS 